### ISSUE TITLE
RangeScrollbar - marks only appearing after resize

### ISSUE THREAD

**Issue by MikeAtETI** [Ttxman/WpfRangeControls#2]
I suspect this is probably user error, but in case anyone has come across it before:

We have a RangeScrollBar which binds to listview as a vertical scrollbar. In this model it has 10 marks added.

![image](https://user-images.githubusercontent.com/3604092/103356766-85d21c00-4aa9-11eb-914d-3f92e2028789.png)

If I resize the window once it is visible, they all appear:

![image](https://user-images.githubusercontent.com/3604092/103356798-96829200-4aa9-11eb-8d1b-5416aee91bdc.png)

Sticking breakpoints in the binding, the 10 objects it binds to are in the right list to be databound from the moment the DataContext is constructed.

**Comment by Ttxman** [comment]
Do you have maximum and minimum (or maybe height, I cant remember how I implemented it..) bound correctly on first screenshot? It seems to me that all marks are rendered at zero postion with center alignment. It would (probably) do that, when min and max are zero when computing the positions...

**Comment by MikeAtETI** [comment]
Using a tracingvalueconverter i've been able to confirm the RangeScrollbar gets a maximum bound at creation, but the RangePanel MeasureOverride gets called before it binds the maximum from the scrollbar.

If I override RangePanel Maximum to work its way up the VisualTree like so : 

            get 
            {
                var rangeScrollbar = FindParent<RangeItemsControl>(this);
                if (rangeScrollbar != null)
                {
                     return (double)rangeScrollbar.GetValue(MaximumProperty);
                }

                return (double)GetValue(MaximumProperty); 
            }

It works, but only for this very specific scenario.

**Comment by Ttxman** [comment]
In that case I think adding `FrameworkPropertyMetadataOptions.AffectsMeasure` To `FrameworkPropertyMetadata` of `Minimum` and `Maximum` DependencyProperties on `RangePanel` should force re-measure with the binding and it should fix your problems

**Comment by MikeAtETI** [comment]
I can confirm that resolves it

**Comment by Ttxman** [comment]
Ty for the fix.
